name: Publish to production

on:
  push:
    branches: [main]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH2 }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "${{ secrets.REMOTE_DIR_MAIN }}plugins/bookid"
